handle console.error(new Error('...'))
this was leaking through:
  [next-logger] createStrictArgShuffler: first console arg must be a string (it's currently a object)
                to ensure logs are easy to search and filter,
                assuming logMethod hook will handle this:
  [
    Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
        at Server.setupListenHandle [as _listen2] (node:net:1330:16)
        ...
      code: 'EADDRINUSE',
      errno: -48,
      syscall: 'listen',
      address: '0.0.0.0',
      port: 3000
    }
  ]
Pino object:
  {
    '0': {
      code: 'EADDRINUSE',
      errno: -48,
      syscall: 'listen',
      address: '0.0.0.0',
      port: 3000
    },
    level: 50,
    time: 1650069194014,
    pid: 79906,
    hostname: 'MacBook-Air',
    name: 'next-logger-strict-console',
    prefix: 'error'
  }